### PR TITLE
Add swipe support (swipe to next/prev image).

### PR DESCRIPTION
**Pull request by SchwarzwaldFalke**
This pull request adds swipe support (using ngTouch) and it disables image select/drag to avoid accidental select/drag during swipe.

### CODE REVIEW

**Comment by jkuri** [comment]
Hi @SchwarzwaldFalke, thank you for your PR! Is this tested and it works?

**Comment by SchwarzwaldFalke** [comment]
Hi @jkuri,

I just added an additional fix to disable image drag.
You can view the current version here:
https://plnkr.co/edit/wTguJV
https://embed.plnkr.co/wTguJV/

If angular touch isn't included the ng-swipe-left and ng-swipe-right are just ignored, so this shouldn't be a problem.

**Comment by jkuri** [comment]
Actually there is some JS error on plunker so I cannot see the preview, but I checked the code and it looks good. Thank you for this fix. Merging.

**Comment by jkuri** [comment]
Btw, are you interested in further development of this component?

**Comment by SchwarzwaldFalke** [comment]
Thanks!
Strange that Plunkr doesn't work.
Here's another example: http://bessei-it.eu/ng-gallery/swipe/

Further development:
Push access would be really great. I hope I find some more time to add more features.

**Pull request merged**
